### ISSUE TITLE
It is impossible to install the apk file of new build if the application is already installed

### ISSUE THREAD

**Issue by YuryiDasevich** [tasks-delivery/craft-dish#68]
**Build version:** 
1.0.56

**Severity:**
Low;

**Description:** APK file with new build does not replace the existing version in the emulator;
Actual result: new version of APK is not installed and did not replace the old one;
Expected result: when you install APK, the old version is replaced by a new one automatically;

**Preconditions:**
Nexus 6P API 27 as test environment;

**Steps to reproduce:**
1.Drag and drop new version of the APK file into device where the application is already installed;
2.Wait till the installation process end;

**Workaround:** 
New APK file could be installed after removing application from device;

**Attachments:**

![-](https://user-images.githubusercontent.com/45947708/51127569-ce4d8c00-1836-11e9-96c8-5889efbbd4ff.png)

**Comment by ordeh** [comment]
Hi @YuryiDasevich  ,
This issue was fixed in https://github.com/tasks-delivery/craft-dish/issues/21

Implemented in build:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/23476070

Apk:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/23476070/artifacts

**Comment by YuryiDasevich** [comment]
Hi @ordeh,
I still have this issue in Build 1.0.159.
Env.: Nexus 6P API 27 Android v8.1
![1](https://user-images.githubusercontent.com/45947708/55287260-25331e00-53af-11e9-897c-7bb959f4cd81.PNG)

**Comment by ordeh** [comment]
Fixed in build:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/33507755

Apk:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/33507755/artifacts

**Comment by xBaNzYx** [comment]
Hi @ordeh
Application version 1.0.284 was tested.
Environment: Nexus 6P API 27 Android v8.1
[Bug](https://github.com/tasks-delivery/craft-dish/issues/68#issuecomment-478325327) was not detected.
